/**
 * Cleanup Script: Reset auto-generated channel profiles
 * 
 * This script identifies users whose channel profiles were erroneously
 * auto-generated by the previous migration script (e.g. channelHandle matching
 * contact/email or channelDescription === 'Welcome to my channel!') and who
 * have no uploaded content, and resets their channel fields to null.
 * 
 * Usage:
 *   node scripts/cleanupAutoGeneratedProfiles.js --dry-run   (preview changes)
 *   node scripts/cleanupAutoGeneratedProfiles.js            (apply changes)
 */

import mongoose from 'mongoose';
import User from '../models/user.model.js';
import Content from '../models/content.model.js';
import dotenv from 'dotenv';

dotenv.config();

const MONGODB_URI = process.env.MONGO_URI || 'mongodb://localhost:27017';
const isDryRun = process.argv.includes('--dry-run');

async function cleanupAutoGeneratedProfiles() {
    try {
        console.log(`\n🚀 Starting cleanup for auto-generated channel profiles ${isDryRun ? '(DRY RUN MODE)' : ''}...\n`);

        await mongoose.connect(MONGODB_URI);
        console.log('✅ Connected to MongoDB\n');

        // Find users with channelName or channelHandle
        const usersWithChannel = await User.find({
            $or: [
                { channelName: { $exists: true, $ne: null, $ne: '' } },
                { channelHandle: { $exists: true, $ne: null, $ne: '' } },
            ]
        }).select('_id userName contact channelName channelHandle channelDescription').lean();

        console.log(`📊 Found ${usersWithChannel.length} total users with channels. Checking for auto-generated profiles...\n`);

        let resetCount = 0;
        let skippedCount = 0;

        for (const user of usersWithChannel) {
            // Check if user has uploaded any content
            const contentCount = await Content.countDocuments({ userId: user._id });

            // If user has uploaded content, they are an active creator -> do NOT touch
            if (contentCount > 0) {
                skippedCount++;
                continue;
            }

            // Check if channel was auto-generated:
            // 1. channelDescription === 'Welcome to my channel!'
            // 2. OR channelHandle is derived from contact email (e.g., contact stripped of symbols)
            const strippedContact = user.contact ? user.contact.replace(/[^a-z0-9_]/gi, '').toLowerCase() : '';
            const isAutoDescription = user.channelDescription === 'Welcome to my channel!';
            const isContactHandle = Boolean(strippedContact && user.channelHandle && user.channelHandle.startsWith(strippedContact.slice(0, 8)));

            if (isAutoDescription || isContactHandle) {
                console.log(`  🔄 Found auto-generated profile for User: ${user.userName || user._id}`);
                console.log(`     Contact: ${user.contact}`);
                console.log(`     Channel Name: ${user.channelName}`);
                console.log(`     Channel Handle: @${user.channelHandle}`);
                console.log(`     Channel Desc: ${user.channelDescription}`);

                if (!isDryRun) {
                    await User.findByIdAndUpdate(user._id, {
                        $unset: {
                            channelName: 1,
                            channelHandle: 1,
                            channelDescription: 1
                        }
                    });
                    console.log(`     ✅ Reset channel fields to null\n`);
                } else {
                    console.log(`     [DRY RUN] Would reset channel fields\n`);
                }
                resetCount++;
            } else {
                skippedCount++;
            }
        }

        console.log(`\n${'='.repeat(60)}`);
        console.log(`📈 Cleanup Summary:${isDryRun ? ' (DRY RUN)' : ''}`);
        console.log(`   Total profiles inspected: ${usersWithChannel.length}`);
        console.log(`   ✅ Profiles ${isDryRun ? 'identified for reset' : 'reset'}: ${resetCount}`);
        console.log(`   ⏭️  Legitimate creator profiles kept: ${skippedCount}`);
        console.log(`${'='.repeat(60)}\n`);

        await mongoose.connection.close();
        console.log('✅ Database connection closed');

    } catch (error) {
        console.error('❌ Cleanup script error:', error.message);
        process.exit(1);
    }
}

cleanupAutoGeneratedProfiles();
